### ISSUE TITLE
I can not connect

### ISSUE THREAD

**Issue by kotenok2000** [gridcoin/Gridcoin-Research#583]
I can not connect to the gridcoin
[debug.txt](https://github.com/gridcoin/Gridcoin-Research/files/1277598/debug.txt)
i am from russia.

**Comment by tomasbrod** [comment]
Well there is nothing related to connection in the debug log. Probably you shut it down too fast. Try adding some `addnode`s to the config. Russia is not KĽDR, it should work there.
I can see that you are loading from 0, currently, due to bug, you MUST use snapshot to sync. It is also faster that way.

**Comment by TheCharlatan** [comment]
Best is to add this entire addnode config: http://wiki.gridcoin.us/List_of_Addnodes

**Comment by tomasbrod** [comment]
Users in IRC think that: The bootstrap from the normal servers is not working.

**Comment by kotenok2000** [comment]
thank  you. i think nodes list helped.

**Comment by MagixInTheAir** [comment]
Is it solved now ? It should be closed then :)
