### ISSUE TITLE
Critical Wallet Problem - gridcoinresearch.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by gettingmad** [gridcoin/Gridcoin-Research#839]
My wallet was synced and staking. It crashed entirely and closed while leaving this message; 

"gridcoinresearch.exe - Entry Point Not Found"
The procedure entry point _ZdlPvj could not be located in the dynamic link library D:\WalletLocation\Qt5Charts.dll.

https://i.imgur.com/UrNqePS.png
(Windows 8, latest Wallet Version 3.7.3.0 cant confirm that but I just updated 2 days ago)

It was running as it should for over a month, aside from the countless shutdowns (Application Not Responding), nerve racking BS we are all experiencing.  

I tried to run grcupgrade.bat and it ran yet same message surfaced after. I think this is the end of my Gridcoin road, I have had enough. I am going to put a fresh wallet on a different client, wait for it to sync and pull this wallet from the backup file then transfer all of it to Polo and wait 3 GD days for 999 Confirmations as I turn it into something with a stable wallet and easier exchange ability. I tried Gridcoin, I tried...

**Comment by denravonska** [comment]
This is due to file tree restructuring in the 3.7 wallet, which should also fix the shutdowns you have experiencing. The reason is that the upgrader is unable to handle the new tree, something which will be addressed in upcoming versions where the upgrader is rewritten to utilize github instead. As of the 3.7 series the upgrader is opt-in so if you have not explicitly enabled it in the config it should not bother you.

I suggest you download the MSI from https://gridcoin.us and try it out. The whole point of the 3.7.x series has been to stabilize and reduce forks. Unfortunately the od upgrader was out of the current devs' control so it has been scheduled for rewrite.

**Comment by gettingmad** [comment]
Greatly appretiating your reply danravonska. Is there a string i can put on the .exe to get past this?

**Comment by denravonska** [comment]
Well, the old upgrader left you in a semi-broken state. If you download the [MSI installer](https://download.gridcoin.us/download/downloadstake/GridcoinResearch.msi) and install you should be good to go with 3.7.3.0.

**Comment by gettingmad** [comment]
Thank You

**Comment by gettingmad** [comment]
Its fixed thanks, I will stick around and try this wallet out now. How can i close this issue?

**Comment by denravonska** [comment]
Cool, thanks! Hit us up on Slack if you have further issues. Let me know if you need an invite.

**Comment by gettingmad** [comment]
My stomach is right side up again.
Thanks man. Really, thanks alot.

https://i.imgur.com/eWmJnoF.png

**Comment by gettingmad** [comment]
Having issues with the wallet again. Im stuck on block 1145355. Im using the last msi you linked above. Halford 3.7.3.0-unk-317 I cant seem to catch the blockchain.

**Comment by gettingmad** [comment]
It managed to catch up and sync, however it will go out of sync after running fine after a while. I have to restart it far too often for a coin I want to have a content stake running 24/7.
